# Generated by Django 3.2.7 on 2021-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisorbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_time', models.DateTimeField()),
            ],
        ),
    ]
